/**
 * Ferrari 296 GT3. Some body parts exported for both sides, others as the +X half;
 * all four wheels complete, but left and right calipers sit at slightly different angles.
 */
export default {
  input: "assets/models/car/Ferrari296GTBGT3.glb",
  output: "assets/models/car/Ferrari296GTBGT3.game.glb",
  forward: "+z",
  /**
   * Steering wheel and roll cage (hidden behind the opaque glass), duplicate copies of
   * the body shell and a fender decal with other materials, and stray template parts.
   */
  removedNodes:
    /^(Torus|NurbsPath\.01[5-8]|High poly basemesh\.00[12]|front fender\.00[89]|roof\.004|panels\.035|grillage front side)$/,
  droppedMaterials: [
    // Alpha-textured stickers: without their texture they'd render as solid rectangles.
    "1200px-Ferrari-Logo.svg",
    "ferrari logo",
    "Material.006",
    "N arrow logo.001",
    // Bulbs, LED matrix and wiring behind the opaque headlight glass.
    "glass HL LED Matrice",
    "copper plate HL",
    "chrome 2.002",
    "glass light Bulb HL",
    "HL Bulb Glow",
    "cables HL",
    "Steel HL.001",
    "Steel HL.002",
    "Steel Flakes",
    "Steel HL Logo",
    "Plastic HL",
    "Material.007",
  ],
  mirror: "unpaired",
  mirrorWheels: false,
  wheels: {
    mode: "materials",
    tire: ["SideWall-8K_Material.002"],
    spin: ["wheel paint", "Material.008", "Ceramic brake disc", "Metal.006", "Metal.002", "Nickel", "Bronze"],
    brake: [
      "Calipers",
      "1 car paint.000",
      "1 car paint.003",
      "1 car paint.007",
      "1 car paint.008",
      "1 car paint.009",
      "1 car paint.010",
      "Material.005",
    ],
  },
  roles: {
    "Car Paint.005": "paint",
    "Car Paint.006": "paint",
    "Carbon Fibre.003": "accent",
    "Carbon Fibre.004": "accent",
    "Carbon Fibre.005": "accent",
    "Carbon Fibre.006": "accent",
    "Carbon Fibre.007": "accent",
    "Carbon Fibre.008": "accent",
    "Carbon Fibre.009": "accent",
    "Black Paint.001": "accent",
    "Plastic Base 01.002": "trim",
    "Plastic Base 01.003": "trim",
    "Black plastic PL.005": "trim",
    "Black plastic PL.006": "trim",
    "Plastic Window Trim.001": "trim",
    "Plastic Window Trim.003": "trim",
    Mesh: "trim",
    "Nurburgring logo diffuser": "trim",
    "inside mesh.001": "trim",
    "Material.013": "trim",
    "black rubber.001": "trim",
    "piano black": "trim",
    "piano black.001": "trim",
    Radar: "trim",
    "Radar metal": "trim",
    "": "trim",
    "Glass.001": "glass",
    Glass: "glass",
    "Glass rear window": "glass",
    "Glass side windows.001": "glass",
    "Glass.006": "headlight",
    "DRL Emission material.002": "headlight",
    "Carlight triangle chrome white": "headlight",
    "Glass Taillights.001": "headlight",
    "taillights outer glass": "taillight",
    "Glass Taillights": "taillight",
    "DRL Emission material": "taillight",
    "DRL Emission material.003": "taillight",
    "DRL Emission material.004": "taillight",
    "Glass.005": "taillight",
    "Orange Glass side indicators": "signal",
    "Chrome.003": "chrome",
    "Chrome.004": "chrome",
    "chrome 2.001": "chrome",
    "nickel.001": "chrome",
    "Licence plate metal": "chrome",
    "ferrari badge": "chrome",
    "Camera lens": "chrome",
    "Material.012": "chrome",
    "Metal.002": "mechanical",
    "Metal05 PBR.002": "mechanical",
    "Metal05 PBR.003": "mechanical",
    "Aluminium rope.001": "mechanical",
    // Wheel materials, in case a triangle falls outside every wheel.
    "Metal.006": "mechanical",
    "Ceramic brake disc": "disc",
    "wheel paint": "rim",
    "Material.008": "chrome",
    Nickel: "chrome",
    Bronze: "disc",
    "SideWall-8K_Material.002": "tire",
    Calipers: "caliper",
    "1 car paint.000": "mechanical",
    "1 car paint.003": "mechanical",
    "1 car paint.007": "mechanical",
    "1 car paint.008": "mechanical",
    "1 car paint.009": "mechanical",
    "1 car paint.010": "mechanical",
    "Material.005": "mechanical",
  },
  wheelRoles: { "Material.008": "rim", "Metal.006": "rimInner", "Metal.002": "rimInner" },
  /** Italian flag stripes and the number plate; Blender left them white. */
  fixedColors: {
    "Green Paint": "#009246",
    "White Paint": "#f2f3ef",
    "Red Paint": "#c8102e",
    "glossy plastic.001": null,
    "License plate": "#e8e8e8",
  },
  /** Perforated grilles (~80k triangles of holes): read as solid dark panels from the chase camera. */
  sloppyMaterials: { Mesh: 2000 },
  /** Mirror indicator strip (in a lamp material). */
  nodeRoles: { "Mirros basemesh.004": "signal" },
  /** Livery on the bodywork: lift it clear so it doesn't z-fight. */
  liftMaterials: { "White Paint": 0.006, "Green Paint": 0.006, "Red Paint": 0.006 },
  /** The front light bar uses a "Glass Taillights" material. */
  lampsByPosition: true,
  simplifyError: { body: 0.003, wheel: 0.006 },
};
